<?php


/**
 * OrderAddressModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;



use \ArrayAccess;


use \Swagger\Client\ObjectSerializer;

/**
 * OrderAddressModel Class Doc Comment
 *
 * @category Class

 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderAddressModel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderAddressModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'original_invoice' => '\Swagger\Client\Model\AddressModel''original_delivery' => '\Swagger\Client\Model\AddressModel''customer_invoice' => '\Swagger\Client\Model\AddressModel''customer_delivery' => '\Swagger\Client\Model\AddressModel''payment_method_invoice' => '\Swagger\Client\Model\AddressModel''payment_method_delivery' => '\Swagger\Client\Model\AddressModel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'original_invoice' => null'original_delivery' => null'customer_invoice' => null'customer_delivery' => null'payment_method_invoice' => null'payment_method_delivery' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'original_invoice' => 'originalInvoice''original_delivery' => 'originalDelivery''customer_invoice' => 'customerInvoice''customer_delivery' => 'customerDelivery''payment_method_invoice' => 'paymentMethodInvoice''payment_method_delivery' => 'paymentMethodDelivery'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'original_invoice' => 'setOriginalInvoice''original_delivery' => 'setOriginalDelivery''customer_invoice' => 'setCustomerInvoice''customer_delivery' => 'setCustomerDelivery''payment_method_invoice' => 'setPaymentMethodInvoice''payment_method_delivery' => 'setPaymentMethodDelivery'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'original_invoice' => 'getOriginalInvoice''original_delivery' => 'getOriginalDelivery''customer_invoice' => 'getCustomerInvoice''customer_delivery' => 'getCustomerDelivery''payment_method_invoice' => 'getPaymentMethodInvoice''payment_method_delivery' => 'getPaymentMethodDelivery'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];
    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        
        
        $this->container['original_invoice'] = isset($data['original_invoice']) ? $data['original_invoice'] : null;
        
        $this->container['original_delivery'] = isset($data['original_delivery']) ? $data['original_delivery'] : null;
        
        $this->container['customer_invoice'] = isset($data['customer_invoice']) ? $data['customer_invoice'] : null;
        
        $this->container['customer_delivery'] = isset($data['customer_delivery']) ? $data['customer_delivery'] : null;
        
        $this->container['payment_method_invoice'] = isset($data['payment_method_invoice']) ? $data['payment_method_invoice'] : null;
        
        $this->container['payment_method_delivery'] = isset($data['payment_method_delivery']) ? $data['payment_method_delivery'] : null;
        
        
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        
        
        $invalidProperties = [];
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return true;
    }

    

    /**
     * Gets original_invoice
     *
     * @return \Swagger\Client\Model\AddressModel
     */
    public function getOriginalInvoice()
    {
        return $this->container['original_invoice'];
    }

    /**
     * Sets original_invoice
     *
     * @param \Swagger\Client\Model\AddressModel $original_invoice original_invoice
     *
     * @return $this
     */
    public function setOriginalInvoice($original_invoice)
    {
        
        
        $this->container['original_invoice'] = $original_invoice;

        return $this;
    }
    

    /**
     * Gets original_delivery
     *
     * @return \Swagger\Client\Model\AddressModel
     */
    public function getOriginalDelivery()
    {
        return $this->container['original_delivery'];
    }

    /**
     * Sets original_delivery
     *
     * @param \Swagger\Client\Model\AddressModel $original_delivery original_delivery
     *
     * @return $this
     */
    public function setOriginalDelivery($original_delivery)
    {
        
        
        $this->container['original_delivery'] = $original_delivery;

        return $this;
    }
    

    /**
     * Gets customer_invoice
     *
     * @return \Swagger\Client\Model\AddressModel
     */
    public function getCustomerInvoice()
    {
        return $this->container['customer_invoice'];
    }

    /**
     * Sets customer_invoice
     *
     * @param \Swagger\Client\Model\AddressModel $customer_invoice customer_invoice
     *
     * @return $this
     */
    public function setCustomerInvoice($customer_invoice)
    {
        
        
        $this->container['customer_invoice'] = $customer_invoice;

        return $this;
    }
    

    /**
     * Gets customer_delivery
     *
     * @return \Swagger\Client\Model\AddressModel
     */
    public function getCustomerDelivery()
    {
        return $this->container['customer_delivery'];
    }

    /**
     * Sets customer_delivery
     *
     * @param \Swagger\Client\Model\AddressModel $customer_delivery customer_delivery
     *
     * @return $this
     */
    public function setCustomerDelivery($customer_delivery)
    {
        
        
        $this->container['customer_delivery'] = $customer_delivery;

        return $this;
    }
    

    /**
     * Gets payment_method_invoice
     *
     * @return \Swagger\Client\Model\AddressModel
     */
    public function getPaymentMethodInvoice()
    {
        return $this->container['payment_method_invoice'];
    }

    /**
     * Sets payment_method_invoice
     *
     * @param \Swagger\Client\Model\AddressModel $payment_method_invoice payment_method_invoice
     *
     * @return $this
     */
    public function setPaymentMethodInvoice($payment_method_invoice)
    {
        
        
        $this->container['payment_method_invoice'] = $payment_method_invoice;

        return $this;
    }
    

    /**
     * Gets payment_method_delivery
     *
     * @return \Swagger\Client\Model\AddressModel
     */
    public function getPaymentMethodDelivery()
    {
        return $this->container['payment_method_delivery'];
    }

    /**
     * Sets payment_method_delivery
     *
     * @param \Swagger\Client\Model\AddressModel $payment_method_delivery payment_method_delivery
     *
     * @return $this
     */
    public function setPaymentMethodDelivery($payment_method_delivery)
    {
        
        
        $this->container['payment_method_delivery'] = $payment_method_delivery;

        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


