<?php


/**
 * ProductVariantAttributeValueModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;



use \ArrayAccess;


use \Swagger\Client\ObjectSerializer;

/**
 * ProductVariantAttributeValueModel Class Doc Comment
 *
 * @category Class

 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductVariantAttributeValueModel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProductVariantAttributeValueModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'attribute_value_id' => 'int''sku_suffix' => 'string''sort_index' => 'int''languages' => '\Swagger\Client\Model\ProductVariantAttributeValueLanguageModel[]''attribute' => '\Swagger\Client\Model\ProductVariantAttributeModel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'attribute_value_id' => 'int32''sku_suffix' => null'sort_index' => 'int32''languages' => null'attribute' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attribute_value_id' => 'attributeValueId''sku_suffix' => 'skuSuffix''sort_index' => 'sortIndex''languages' => 'languages''attribute' => 'attribute'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attribute_value_id' => 'setAttributeValueId''sku_suffix' => 'setSkuSuffix''sort_index' => 'setSortIndex''languages' => 'setLanguages''attribute' => 'setAttribute'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attribute_value_id' => 'getAttributeValueId''sku_suffix' => 'getSkuSuffix''sort_index' => 'getSortIndex''languages' => 'getLanguages''attribute' => 'getAttribute'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];
    

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        
        
        $this->container['attribute_value_id'] = isset($data['attribute_value_id']) ? $data['attribute_value_id'] : null;
        
        $this->container['sku_suffix'] = isset($data['sku_suffix']) ? $data['sku_suffix'] : null;
        
        $this->container['sort_index'] = isset($data['sort_index']) ? $data['sort_index'] : 0;
        
        $this->container['languages'] = isset($data['languages']) ? $data['languages'] : null;
        
        $this->container['attribute'] = isset($data['attribute']) ? $data['attribute'] : null;
        
        
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        
        
        $invalidProperties = [];
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return true;
    }

    

    /**
     * Gets attribute_value_id
     *
     * @return int
     */
    public function getAttributeValueId()
    {
        return $this->container['attribute_value_id'];
    }

    /**
     * Sets attribute_value_id
     *
     * @param int $attribute_value_id The id for this attribute value
     *
     * @return $this
     */
    public function setAttributeValueId($attribute_value_id)
    {
        
        
        $this->container['attribute_value_id'] = $attribute_value_id;

        return $this;
    }
    

    /**
     * Gets sku_suffix
     *
     * @return string
     */
    public function getSkuSuffix()
    {
        return $this->container['sku_suffix'];
    }

    /**
     * Sets sku_suffix
     *
     * @param string $sku_suffix The suggested suffix for new Variants using this attribute value
     *
     * @return $this
     */
    public function setSkuSuffix($sku_suffix)
    {
        
        
        $this->container['sku_suffix'] = $sku_suffix;

        return $this;
    }
    

    /**
     * Gets sort_index
     *
     * @return int
     */
    public function getSortIndex()
    {
        return $this->container['sort_index'];
    }

    /**
     * Sets sort_index
     *
     * @param int $sort_index The sort order for this attribute value
     *
     * @return $this
     */
    public function setSortIndex($sort_index)
    {
        
        
        $this->container['sort_index'] = $sort_index;

        return $this;
    }
    

    /**
     * Gets languages
     *
     * @return \Swagger\Client\Model\ProductVariantAttributeValueLanguageModel[]
     */
    public function getLanguages()
    {
        return $this->container['languages'];
    }

    /**
     * Sets languages
     *
     * @param \Swagger\Client\Model\ProductVariantAttributeValueLanguageModel[] $languages A collection of attribute value languages
     *
     * @return $this
     */
    public function setLanguages($languages)
    {
        
        
        $this->container['languages'] = $languages;

        return $this;
    }
    

    /**
     * Gets attribute
     *
     * @return \Swagger\Client\Model\ProductVariantAttributeModel
     */
    public function getAttribute()
    {
        return $this->container['attribute'];
    }

    /**
     * Sets attribute
     *
     * @param \Swagger\Client\Model\ProductVariantAttributeModel $attribute attribute
     *
     * @return $this
     */
    public function setAttribute($attribute)
    {
        
        
        $this->container['attribute'] = $attribute;

        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


