<?php


/**
 * AddressModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AddressModelTest Class Doc Comment
 *
 * @category    Class
 * @description AddressModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddressModel"
     */
    public function testAddressModel()
    {
    }


    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }


    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }


    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }


    /**
     * Test attribute "care_of"
     */
    public function testPropertyCareOf()
    {
    }


    /**
     * Test attribute "attention"
     */
    public function testPropertyAttention()
    {
    }


    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }


    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }


    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }


    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }


    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }


    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }


    /**
     * Test attribute "phone_no"
     */
    public function testPropertyPhoneNo()
    {
    }


    /**
     * Test attribute "mobile_phone_no"
     */
    public function testPropertyMobilePhoneNo()
    {
    }

}


