<?php


/**
 * CustomerModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerModelTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerModel"
     */
    public function testCustomerModel()
    {
    }


    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }


    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }


    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }


    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }


    /**
     * Test attribute "national_id_no"
     */
    public function testPropertyNationalIdNo()
    {
    }


    /**
     * Test attribute "vat_no"
     */
    public function testPropertyVatNo()
    {
    }


    /**
     * Test attribute "custom_info1"
     */
    public function testPropertyCustomInfo1()
    {
    }


    /**
     * Test attribute "custom_info2"
     */
    public function testPropertyCustomInfo2()
    {
    }


    /**
     * Test attribute "modified_at"
     */
    public function testPropertyModifiedAt()
    {
    }


    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {
    }


    /**
     * Test attribute "approved_at"
     */
    public function testPropertyApprovedAt()
    {
    }


    /**
     * Test attribute "pricelist_id"
     */
    public function testPropertyPricelistId()
    {
    }


    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }


    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }


    /**
     * Test attribute "external_services"
     */
    public function testPropertyExternalServices()
    {
    }

}


