<?php


/**
 * MediaFileModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MediaFileModelTest Class Doc Comment
 *
 * @category    Class
 * @description MediaFileModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MediaFileModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MediaFileModel"
     */
    public function testMediaFileModel()
    {
    }


    /**
     * Test attribute "media_file_id"
     */
    public function testPropertyMediaFileId()
    {
    }


    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }


    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }


    /**
     * Test attribute "modified_at"
     */
    public function testPropertyModifiedAt()
    {
    }


    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }


    /**
     * Test attribute "mime"
     */
    public function testPropertyMime()
    {
    }


    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }


    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }


    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

}


