<?php


/**
 * OrderUpdateModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderUpdateModelTest Class Doc Comment
 *
 * @category    Class
 * @description OrderUpdateModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderUpdateModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderUpdateModel"
     */
    public function testOrderUpdateModel()
    {
    }


    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }


    /**
     * Test attribute "modified_at"
     */
    public function testPropertyModifiedAt()
    {
    }


    /**
     * Test attribute "base_currency_code"
     */
    public function testPropertyBaseCurrencyCode()
    {
    }


    /**
     * Test attribute "shop_country_code"
     */
    public function testPropertyShopCountryCode()
    {
    }


    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }


    /**
     * Test attribute "total_vat"
     */
    public function testPropertyTotalVat()
    {
    }


    /**
     * Test attribute "amount_to_pay"
     */
    public function testPropertyAmountToPay()
    {
    }


    /**
     * Test attribute "total_amount_in_base_currency"
     */
    public function testPropertyTotalAmountInBaseCurrency()
    {
    }


    /**
     * Test attribute "total_vat_in_base_currency"
     */
    public function testPropertyTotalVatInBaseCurrency()
    {
    }


    /**
     * Test attribute "amount_to_pay_in_base_currency"
     */
    public function testPropertyAmountToPayInBaseCurrency()
    {
    }


    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }


    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }


    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
    }


    /**
     * Test attribute "on_order_status_change_send_email"
     */
    public function testPropertyOnOrderStatusChangeSendEmail()
    {
    }


    /**
     * Test attribute "on_order_status_change_process_payment"
     */
    public function testPropertyOnOrderStatusChangeProcessPayment()
    {
    }


    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {
    }


    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }


    /**
     * Test attribute "payment_method_id_code"
     */
    public function testPropertyPaymentMethodIdCode()
    {
    }


    /**
     * Test attribute "payment_method_name"
     */
    public function testPropertyPaymentMethodName()
    {
    }


    /**
     * Test attribute "payment_fee"
     */
    public function testPropertyPaymentFee()
    {
    }


    /**
     * Test attribute "payment_vat_rate"
     */
    public function testPropertyPaymentVatRate()
    {
    }


    /**
     * Test attribute "shipping_method_name"
     */
    public function testPropertyShippingMethodName()
    {
    }


    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }


    /**
     * Test attribute "shipping_vat_rate"
     */
    public function testPropertyShippingVatRate()
    {
    }


    /**
     * Test attribute "total_weight"
     */
    public function testPropertyTotalWeight()
    {
    }


    /**
     * Test attribute "custom_info1"
     */
    public function testPropertyCustomInfo1()
    {
    }


    /**
     * Test attribute "custom_info2"
     */
    public function testPropertyCustomInfo2()
    {
    }


    /**
     * Test attribute "custom_info3"
     */
    public function testPropertyCustomInfo3()
    {
    }


    /**
     * Test attribute "custom_info4"
     */
    public function testPropertyCustomInfo4()
    {
    }


    /**
     * Test attribute "discount_code"
     */
    public function testPropertyDiscountCode()
    {
    }


    /**
     * Test attribute "amount_paid"
     */
    public function testPropertyAmountPaid()
    {
    }


    /**
     * Test attribute "amount_paid_in_base_currency"
     */
    public function testPropertyAmountPaidInBaseCurrency()
    {
    }


    /**
     * Test attribute "is_complete"
     */
    public function testPropertyIsComplete()
    {
    }


    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }


    /**
     * Test attribute "currency_exchange_rate"
     */
    public function testPropertyCurrencyExchangeRate()
    {
    }


    /**
     * Test attribute "currency_precision"
     */
    public function testPropertyCurrencyPrecision()
    {
    }


    /**
     * Test attribute "lang_code"
     */
    public function testPropertyLangCode()
    {
    }


    /**
     * Test attribute "payment_reference"
     */
    public function testPropertyPaymentReference()
    {
    }


    /**
     * Test attribute "payment_status"
     */
    public function testPropertyPaymentStatus()
    {
    }


    /**
     * Test attribute "is_read"
     */
    public function testPropertyIsRead()
    {
    }


    /**
     * Test attribute "has_comment"
     */
    public function testPropertyHasComment()
    {
    }


    /**
     * Test attribute "internal_comment"
     */
    public function testPropertyInternalComment()
    {
    }


    /**
     * Test attribute "shipping_tracker_type"
     */
    public function testPropertyShippingTrackerType()
    {
    }


    /**
     * Test attribute "shipping_tracking_no"
     */
    public function testPropertyShippingTrackingNo()
    {
    }


    /**
     * Test attribute "original_customer_email"
     */
    public function testPropertyOriginalCustomerEmail()
    {
    }


    /**
     * Test attribute "original_customer_national_id_no"
     */
    public function testPropertyOriginalCustomerNationalIdNo()
    {
    }


    /**
     * Test attribute "original_customer_vat_no"
     */
    public function testPropertyOriginalCustomerVatNo()
    {
    }


    /**
     * Test attribute "original_customer_custom_info1"
     */
    public function testPropertyOriginalCustomerCustomInfo1()
    {
    }


    /**
     * Test attribute "original_customer_custom_info2"
     */
    public function testPropertyOriginalCustomerCustomInfo2()
    {
    }


    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }


    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

}


