<?php


/**
 * OrderItemModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderItemModelTest Class Doc Comment
 *
 * @category    Class
 * @description OrderItemModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderItemModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderItemModel"
     */
    public function testOrderItemModel()
    {
    }


    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }


    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }


    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }


    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }


    /**
     * Test attribute "unit_symbol"
     */
    public function testPropertyUnitSymbol()
    {
    }


    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }


    /**
     * Test attribute "vat_rate"
     */
    public function testPropertyVatRate()
    {
    }


    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }


    /**
     * Test attribute "discount_type"
     */
    public function testPropertyDiscountType()
    {
    }


    /**
     * Test attribute "sort_index"
     */
    public function testPropertySortIndex()
    {
    }

}


