<?php


/**
 * OrderAddressModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderAddressModelTest Class Doc Comment
 *
 * @category    Class
 * @description OrderAddressModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderAddressModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderAddressModel"
     */
    public function testOrderAddressModel()
    {
    }


    /**
     * Test attribute "original_invoice"
     */
    public function testPropertyOriginalInvoice()
    {
    }


    /**
     * Test attribute "original_delivery"
     */
    public function testPropertyOriginalDelivery()
    {
    }


    /**
     * Test attribute "customer_invoice"
     */
    public function testPropertyCustomerInvoice()
    {
    }


    /**
     * Test attribute "customer_delivery"
     */
    public function testPropertyCustomerDelivery()
    {
    }


    /**
     * Test attribute "payment_method_invoice"
     */
    public function testPropertyPaymentMethodInvoice()
    {
    }


    /**
     * Test attribute "payment_method_delivery"
     */
    public function testPropertyPaymentMethodDelivery()
    {
    }

}


