<?php


/**
 * PaymentMethodModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PaymentMethodModelTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentMethodModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentMethodModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentMethodModel"
     */
    public function testPaymentMethodModel()
    {
    }


    /**
     * Test attribute "payment_method_id"
     */
    public function testPropertyPaymentMethodId()
    {
    }


    /**
     * Test attribute "id_code"
     */
    public function testPropertyIdCode()
    {
    }


    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }


    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }


    /**
     * Test attribute "valid_for_countries"
     */
    public function testPropertyValidForCountries()
    {
    }


    /**
     * Test attribute "valid_countries_selected"
     */
    public function testPropertyValidCountriesSelected()
    {
    }


    /**
     * Test attribute "valid_for_min_items_subtotal"
     */
    public function testPropertyValidForMinItemsSubtotal()
    {
    }


    /**
     * Test attribute "valid_for_max_items_subtotal"
     */
    public function testPropertyValidForMaxItemsSubtotal()
    {
    }


    /**
     * Test attribute "valid_for_min_weight"
     */
    public function testPropertyValidForMinWeight()
    {
    }


    /**
     * Test attribute "valid_for_max_weight"
     */
    public function testPropertyValidForMaxWeight()
    {
    }


    /**
     * Test attribute "valid_for_shipping_methods"
     */
    public function testPropertyValidForShippingMethods()
    {
    }


    /**
     * Test attribute "valid_for_customer_type"
     */
    public function testPropertyValidForCustomerType()
    {
    }


    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

}


