<?php


/**
 * PricelistModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PricelistModelTest Class Doc Comment
 *
 * @category    Class
 * @description PricelistModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PricelistModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PricelistModel"
     */
    public function testPricelistModel()
    {
    }


    /**
     * Test attribute "pricelist_id"
     */
    public function testPropertyPricelistId()
    {
    }


    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }


    /**
     * Test attribute "is_master"
     */
    public function testPropertyIsMaster()
    {
    }


    /**
     * Test attribute "country_codes"
     */
    public function testPropertyCountryCodes()
    {
    }


    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }


    /**
     * Test attribute "parent_pricelist_id"
     */
    public function testPropertyParentPricelistId()
    {
    }


    /**
     * Test attribute "is_customer_pricelist"
     */
    public function testPropertyIsCustomerPricelist()
    {
    }


    /**
     * Test attribute "is_country_pricelist"
     */
    public function testPropertyIsCountryPricelist()
    {
    }

}


