<?php


/**
 * ProductModelUpdatableTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductModelUpdatableTest Class Doc Comment
 *
 * @category    Class
 * @description ProductModelUpdatable
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductModelUpdatableTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductModelUpdatable"
     */
    public function testProductModelUpdatable()
    {
    }


    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }


    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }


    /**
     * Test attribute "default_vat_rate"
     */
    public function testPropertyDefaultVatRate()
    {
    }


    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }


    /**
     * Test attribute "more_info_url"
     */
    public function testPropertyMoreInfoUrl()
    {
    }


    /**
     * Test attribute "manufacturer_id"
     */
    public function testPropertyManufacturerId()
    {
    }


    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {
    }


    /**
     * Test attribute "sort_index"
     */
    public function testPropertySortIndex()
    {
    }


    /**
     * Test attribute "is_back_in_stock_watchable"
     */
    public function testPropertyIsBackInStockWatchable()
    {
    }


    /**
     * Test attribute "has_several_variants"
     */
    public function testPropertyHasSeveralVariants()
    {
    }


    /**
     * Test attribute "modified_at"
     */
    public function testPropertyModifiedAt()
    {
    }


    /**
     * Test attribute "variants"
     */
    public function testPropertyVariants()
    {
    }


    /**
     * Test attribute "media_files"
     */
    public function testPropertyMediaFiles()
    {
    }


    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }


    /**
     * Test attribute "vat_rates"
     */
    public function testPropertyVatRates()
    {
    }


    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }


    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {
    }

}


