<?php


/**
 * ProductCategoryModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductCategoryModelTest Class Doc Comment
 *
 * @category    Class
 * @description ProductCategoryModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductCategoryModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductCategoryModel"
     */
    public function testProductCategoryModel()
    {
    }


    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }


    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }


    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }


    /**
     * Test attribute "sort_index"
     */
    public function testPropertySortIndex()
    {
    }


    /**
     * Test attribute "open_page"
     */
    public function testPropertyOpenPage()
    {
    }


    /**
     * Test attribute "image_file_id"
     */
    public function testPropertyImageFileId()
    {
    }


    /**
     * Test attribute "external_type"
     */
    public function testPropertyExternalType()
    {
    }


    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }


    /**
     * Test attribute "has_children"
     */
    public function testPropertyHasChildren()
    {
    }


    /**
     * Test attribute "languages"
     */
    public function testPropertyLanguages()
    {
    }

}


