<?php


/**
 * ProductVariantModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductVariantModelTest Class Doc Comment
 *
 * @category    Class
 * @description ProductVariantModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductVariantModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductVariantModel"
     */
    public function testProductVariantModel()
    {
    }


    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
    }


    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }


    /**
     * Test attribute "stock_status_id"
     */
    public function testPropertyStockStatusId()
    {
    }


    /**
     * Test attribute "stock_quantity"
     */
    public function testPropertyStockQuantity()
    {
    }


    /**
     * Test attribute "weight_in_kg"
     */
    public function testPropertyWeightInKg()
    {
    }


    /**
     * Test attribute "cost_price"
     */
    public function testPropertyCostPrice()
    {
    }


    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }


    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }


    /**
     * Test attribute "image_file_id"
     */
    public function testPropertyImageFileId()
    {
    }


    /**
     * Test attribute "attribute_value_links"
     */
    public function testPropertyAttributeValueLinks()
    {
    }


    /**
     * Test attribute "prices"
     */
    public function testPropertyPrices()
    {
    }


    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
    }

}


