<?php


/**
 * ShopModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ShopModelTest Class Doc Comment
 *
 * @category    Class
 * @description ShopModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShopModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShopModel"
     */
    public function testShopModel()
    {
    }


    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }


    /**
     * Test attribute "id_code"
     */
    public function testPropertyIdCode()
    {
    }


    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }


    /**
     * Test attribute "default_lang_code"
     */
    public function testPropertyDefaultLangCode()
    {
    }


    /**
     * Test attribute "active_lang_codes"
     */
    public function testPropertyActiveLangCodes()
    {
    }


    /**
     * Test attribute "base_currency"
     */
    public function testPropertyBaseCurrency()
    {
    }


    /**
     * Test attribute "default_customer_country_code"
     */
    public function testPropertyDefaultCustomerCountryCode()
    {
    }


    /**
     * Test attribute "general_default_vat_rate"
     */
    public function testPropertyGeneralDefaultVatRate()
    {
    }


    /**
     * Test attribute "shop_company_name"
     */
    public function testPropertyShopCompanyName()
    {
    }


    /**
     * Test attribute "shop_address"
     */
    public function testPropertyShopAddress()
    {
    }


    /**
     * Test attribute "shop_postal_code"
     */
    public function testPropertyShopPostalCode()
    {
    }


    /**
     * Test attribute "shop_city"
     */
    public function testPropertyShopCity()
    {
    }


    /**
     * Test attribute "shop_org_no"
     */
    public function testPropertyShopOrgNo()
    {
    }


    /**
     * Test attribute "shop_phone_no"
     */
    public function testPropertyShopPhoneNo()
    {
    }


    /**
     * Test attribute "shop_vat_no"
     */
    public function testPropertyShopVatNo()
    {
    }


    /**
     * Test attribute "shop_country_code"
     */
    public function testPropertyShopCountryCode()
    {
    }

}


