<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starweb Shop API v.2
 *
 * This API is only allowed to be used by partners of Starweb AB and further requires explicit permission from both Starweb AB and the shop owner. If you are interested in using it, please contact us at starwebapi@starweb.se
 *
 * OpenAPI spec version: 2.0.0
 * Contact: starwebapi@starweb.se
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.0-rc1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use {{invokerPackage}}\Configuration;
use {{invokerPackage}}\ApiException;
use {{invokerPackage}}\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }
    

    /**
     * Test case for addTagToCustomer
     *
     * .
     *
     */
    public function testAddTagToCustomer()
    {
    }
    

    /**
     * Test case for createAttribute
     *
     * .
     *
     */
    public function testCreateAttribute()
    {
    }
    

    /**
     * Test case for createCustomer
     *
     * .
     *
     */
    public function testCreateCustomer()
    {
    }
    

    /**
     * Test case for createMediaFile
     *
     * .
     *
     */
    public function testCreateMediaFile()
    {
    }
    

    /**
     * Test case for createOrder
     *
     * .
     *
     */
    public function testCreateOrder()
    {
    }
    

    /**
     * Test case for createOrderExternalService
     *
     * .
     *
     */
    public function testCreateOrderExternalService()
    {
    }
    

    /**
     * Test case for createOrderItem
     *
     * .
     *
     */
    public function testCreateOrderItem()
    {
    }
    

    /**
     * Test case for createOrderStatus
     *
     * .
     *
     */
    public function testCreateOrderStatus()
    {
    }
    

    /**
     * Test case for createProduct
     *
     * .
     *
     */
    public function testCreateProduct()
    {
    }
    

    /**
     * Test case for createProductCategory
     *
     * .
     *
     */
    public function testCreateProductCategory()
    {
    }
    

    /**
     * Test case for createProductStockStatus
     *
     * .
     *
     */
    public function testCreateProductStockStatus()
    {
    }
    

    /**
     * Test case for createProductVariant
     *
     * .
     *
     */
    public function testCreateProductVariant()
    {
    }
    

    /**
     * Test case for createProductVariantPricelistPrice
     *
     * .
     *
     */
    public function testCreateProductVariantPricelistPrice()
    {
    }
    

    /**
     * Test case for createProductVatRate
     *
     * .
     *
     */
    public function testCreateProductVatRate()
    {
    }
    

    /**
     * Test case for createProductsCategoryLink
     *
     * .
     *
     */
    public function testCreateProductsCategoryLink()
    {
    }
    

    /**
     * Test case for createProductsLanguage
     *
     * .
     *
     */
    public function testCreateProductsLanguage()
    {
    }
    

    /**
     * Test case for createProductsMediaFileLink
     *
     * .
     *
     */
    public function testCreateProductsMediaFileLink()
    {
    }
    

    /**
     * Test case for createProductsMetaData
     *
     * .
     *
     */
    public function testCreateProductsMetaData()
    {
    }
    

    /**
     * Test case for createProductsVariantsAttributeValues
     *
     * .
     *
     */
    public function testCreateProductsVariantsAttributeValues()
    {
    }
    

    /**
     * Test case for deleteAttribute
     *
     * .
     *
     */
    public function testDeleteAttribute()
    {
    }
    

    /**
     * Test case for deleteAttributeValue
     *
     * .
     *
     */
    public function testDeleteAttributeValue()
    {
    }
    

    /**
     * Test case for deleteCustomer
     *
     * .
     *
     */
    public function testDeleteCustomer()
    {
    }
    

    /**
     * Test case for deleteMediaFile
     *
     * .
     *
     */
    public function testDeleteMediaFile()
    {
    }
    

    /**
     * Test case for deleteOrder
     *
     * .
     *
     */
    public function testDeleteOrder()
    {
    }
    

    /**
     * Test case for deleteOrderAddress
     *
     * .
     *
     */
    public function testDeleteOrderAddress()
    {
    }
    

    /**
     * Test case for deleteOrderExternalService
     *
     * .
     *
     */
    public function testDeleteOrderExternalService()
    {
    }
    

    /**
     * Test case for deleteOrderItem
     *
     * .
     *
     */
    public function testDeleteOrderItem()
    {
    }
    

    /**
     * Test case for deleteOrderStatus
     *
     * .
     *
     */
    public function testDeleteOrderStatus()
    {
    }
    

    /**
     * Test case for deleteProduct
     *
     * .
     *
     */
    public function testDeleteProduct()
    {
    }
    

    /**
     * Test case for deleteProductCategory
     *
     * .
     *
     */
    public function testDeleteProductCategory()
    {
    }
    

    /**
     * Test case for deleteProductStockStatus
     *
     * .
     *
     */
    public function testDeleteProductStockStatus()
    {
    }
    

    /**
     * Test case for deleteProductsCategoryLink
     *
     * .
     *
     */
    public function testDeleteProductsCategoryLink()
    {
    }
    

    /**
     * Test case for deleteProductsLanguage
     *
     * .
     *
     */
    public function testDeleteProductsLanguage()
    {
    }
    

    /**
     * Test case for deleteProductsMediaFileLink
     *
     * .
     *
     */
    public function testDeleteProductsMediaFileLink()
    {
    }
    

    /**
     * Test case for deleteProductsMetaData
     *
     * .
     *
     */
    public function testDeleteProductsMetaData()
    {
    }
    

    /**
     * Test case for deleteProductsVariant
     *
     * .
     *
     */
    public function testDeleteProductsVariant()
    {
    }
    

    /**
     * Test case for deleteProductsVariantsPricelistPrice
     *
     * .
     *
     */
    public function testDeleteProductsVariantsPricelistPrice()
    {
    }
    

    /**
     * Test case for deleteProductsVatRate
     *
     * .
     *
     */
    public function testDeleteProductsVatRate()
    {
    }
    

    /**
     * Test case for generateFetchAccessToken
     *
     * .
     *
     */
    public function testGenerateFetchAccessToken()
    {
    }
    

    /**
     * Test case for getCurrencies
     *
     * .
     *
     */
    public function testGetCurrencies()
    {
    }
    

    /**
     * Test case for getCurrency
     *
     * .
     *
     */
    public function testGetCurrency()
    {
    }
    

    /**
     * Test case for getCustomer
     *
     * .
     *
     */
    public function testGetCustomer()
    {
    }
    

    /**
     * Test case for getCustomerAddress
     *
     * .
     *
     */
    public function testGetCustomerAddress()
    {
    }
    

    /**
     * Test case for getCustomerExternalService
     *
     * .
     *
     */
    public function testGetCustomerExternalService()
    {
    }
    

    /**
     * Test case for getCustomerExternalServices
     *
     * .
     *
     */
    public function testGetCustomerExternalServices()
    {
    }
    

    /**
     * Test case for getCustomerGroups
     *
     * .
     *
     */
    public function testGetCustomerGroups()
    {
    }
    

    /**
     * Test case for getCustomerTag
     *
     * .
     *
     */
    public function testGetCustomerTag()
    {
    }
    

    /**
     * Test case for getCustomerTag_0
     *
     * .
     *
     */
    public function testGetCustomerTag0()
    {
    }
    

    /**
     * Test case for getCustomerTags
     *
     * .
     *
     */
    public function testGetCustomerTags()
    {
    }
    

    /**
     * Test case for getCustomerTags_0
     *
     * .
     *
     */
    public function testGetCustomerTags0()
    {
    }
    

    /**
     * Test case for getMediaFile
     *
     * .
     *
     */
    public function testGetMediaFile()
    {
    }
    

    /**
     * Test case for getMediaFiles
     *
     * .
     *
     */
    public function testGetMediaFiles()
    {
    }
    

    /**
     * Test case for getOrder
     *
     * .
     *
     */
    public function testGetOrder()
    {
    }
    

    /**
     * Test case for getOrderAddress
     *
     * .
     *
     */
    public function testGetOrderAddress()
    {
    }
    

    /**
     * Test case for getOrderComment
     *
     * .
     *
     */
    public function testGetOrderComment()
    {
    }
    

    /**
     * Test case for getOrderComments
     *
     * .
     *
     */
    public function testGetOrderComments()
    {
    }
    

    /**
     * Test case for getOrderExternalService
     *
     * .
     *
     */
    public function testGetOrderExternalService()
    {
    }
    

    /**
     * Test case for getOrderExternalServices
     *
     * .
     *
     */
    public function testGetOrderExternalServices()
    {
    }
    

    /**
     * Test case for getOrderItem
     *
     * .
     *
     */
    public function testGetOrderItem()
    {
    }
    

    /**
     * Test case for getOrderItems
     *
     * .
     *
     */
    public function testGetOrderItems()
    {
    }
    

    /**
     * Test case for getOrderStatus
     *
     * .
     *
     */
    public function testGetOrderStatus()
    {
    }
    

    /**
     * Test case for getOrderStatuses
     *
     * .
     *
     */
    public function testGetOrderStatuses()
    {
    }
    

    /**
     * Test case for getPaymentMethod
     *
     * .
     *
     */
    public function testGetPaymentMethod()
    {
    }
    

    /**
     * Test case for getPaymentMethods
     *
     * .
     *
     */
    public function testGetPaymentMethods()
    {
    }
    

    /**
     * Test case for getPricelist
     *
     * .
     *
     */
    public function testGetPricelist()
    {
    }
    

    /**
     * Test case for getPricelists
     *
     * .
     *
     */
    public function testGetPricelists()
    {
    }
    

    /**
     * Test case for getProduct
     *
     * .
     *
     */
    public function testGetProduct()
    {
    }
    

    /**
     * Test case for getProductCategory
     *
     * .
     *
     */
    public function testGetProductCategory()
    {
    }
    

    /**
     * Test case for getProductManufacturer
     *
     * .
     *
     */
    public function testGetProductManufacturer()
    {
    }
    

    /**
     * Test case for getProductMetaDataType
     *
     * .
     *
     */
    public function testGetProductMetaDataType()
    {
    }
    

    /**
     * Test case for getProductStockStatus
     *
     * .
     *
     */
    public function testGetProductStockStatus()
    {
    }
    

    /**
     * Test case for getProductUnit
     *
     * .
     *
     */
    public function testGetProductUnit()
    {
    }
    

    /**
     * Test case for getProductsAttribute
     *
     * .
     *
     */
    public function testGetProductsAttribute()
    {
    }
    

    /**
     * Test case for getProductsCategoryLink
     *
     * .
     *
     */
    public function testGetProductsCategoryLink()
    {
    }
    

    /**
     * Test case for getProductsLanguage
     *
     * .
     *
     */
    public function testGetProductsLanguage()
    {
    }
    

    /**
     * Test case for getProductsMediaFileLink
     *
     * .
     *
     */
    public function testGetProductsMediaFileLink()
    {
    }
    

    /**
     * Test case for getProductsMetaData
     *
     * .
     *
     */
    public function testGetProductsMetaData()
    {
    }
    

    /**
     * Test case for getProductsVariant
     *
     * .
     *
     */
    public function testGetProductsVariant()
    {
    }
    

    /**
     * Test case for getProductsVariantsAttributeValue
     *
     * .
     *
     */
    public function testGetProductsVariantsAttributeValue()
    {
    }
    

    /**
     * Test case for getProductsVariantsAttributeValue_0
     *
     * .
     *
     */
    public function testGetProductsVariantsAttributeValue0()
    {
    }
    

    /**
     * Test case for getProductsVariantsPricelistPrice
     *
     * .
     *
     */
    public function testGetProductsVariantsPricelistPrice()
    {
    }
    

    /**
     * Test case for getProductsVatRate
     *
     * .
     *
     */
    public function testGetProductsVatRate()
    {
    }
    

    /**
     * Test case for getShippingMethod
     *
     * .
     *
     */
    public function testGetShippingMethod()
    {
    }
    

    /**
     * Test case for getShippingMethods
     *
     * .
     *
     */
    public function testGetShippingMethods()
    {
    }
    

    /**
     * Test case for getShippingTrackingTypes
     *
     * .
     *
     */
    public function testGetShippingTrackingTypes()
    {
    }
    

    /**
     * Test case for getShop
     *
     * .
     *
     */
    public function testGetShop()
    {
    }
    

    /**
     * Test case for listCustomers
     *
     * .
     *
     */
    public function testListCustomers()
    {
    }
    

    /**
     * Test case for listOrderAddresses
     *
     * .
     *
     */
    public function testListOrderAddresses()
    {
    }
    

    /**
     * Test case for listOrders
     *
     * .
     *
     */
    public function testListOrders()
    {
    }
    

    /**
     * Test case for listProductCategories
     *
     * .
     *
     */
    public function testListProductCategories()
    {
    }
    

    /**
     * Test case for listProductManufacturers
     *
     * .
     *
     */
    public function testListProductManufacturers()
    {
    }
    

    /**
     * Test case for listProductMetaDataTypes
     *
     * .
     *
     */
    public function testListProductMetaDataTypes()
    {
    }
    

    /**
     * Test case for listProductStockStatses
     *
     * .
     *
     */
    public function testListProductStockStatses()
    {
    }
    

    /**
     * Test case for listProductUnits
     *
     * .
     *
     */
    public function testListProductUnits()
    {
    }
    

    /**
     * Test case for listProducts
     *
     * .
     *
     */
    public function testListProducts()
    {
    }
    

    /**
     * Test case for listProductsAttributes
     *
     * .
     *
     */
    public function testListProductsAttributes()
    {
    }
    

    /**
     * Test case for listProductsCategoryLinks
     *
     * .
     *
     */
    public function testListProductsCategoryLinks()
    {
    }
    

    /**
     * Test case for listProductsLanguages
     *
     * .
     *
     */
    public function testListProductsLanguages()
    {
    }
    

    /**
     * Test case for listProductsMediaFileLinks
     *
     * .
     *
     */
    public function testListProductsMediaFileLinks()
    {
    }
    

    /**
     * Test case for listProductsMetaData
     *
     * .
     *
     */
    public function testListProductsMetaData()
    {
    }
    

    /**
     * Test case for listProductsVariants
     *
     * .
     *
     */
    public function testListProductsVariants()
    {
    }
    

    /**
     * Test case for listProductsVariantsAttributeValues
     *
     * .
     *
     */
    public function testListProductsVariantsAttributeValues()
    {
    }
    

    /**
     * Test case for listProductsVariantsAttributeValues_0
     *
     * .
     *
     */
    public function testListProductsVariantsAttributeValues0()
    {
    }
    

    /**
     * Test case for listProductsVariantsPricelistPrices
     *
     * .
     *
     */
    public function testListProductsVariantsPricelistPrices()
    {
    }
    

    /**
     * Test case for listProductsVatRates
     *
     * .
     *
     */
    public function testListProductsVatRates()
    {
    }
    

    /**
     * Test case for patchAttribute
     *
     * .
     *
     */
    public function testPatchAttribute()
    {
    }
    

    /**
     * Test case for patchCustomer
     *
     * .
     *
     */
    public function testPatchCustomer()
    {
    }
    

    /**
     * Test case for patchCustomerAddress
     *
     * .
     *
     */
    public function testPatchCustomerAddress()
    {
    }
    

    /**
     * Test case for patchMediaFile
     *
     * .
     *
     */
    public function testPatchMediaFile()
    {
    }
    

    /**
     * Test case for patchOrder
     *
     * .
     *
     */
    public function testPatchOrder()
    {
    }
    

    /**
     * Test case for patchOrderAddress
     *
     * .
     *
     */
    public function testPatchOrderAddress()
    {
    }
    

    /**
     * Test case for patchOrderExternalService
     *
     * .
     *
     */
    public function testPatchOrderExternalService()
    {
    }
    

    /**
     * Test case for patchOrderItem
     *
     * .
     *
     */
    public function testPatchOrderItem()
    {
    }
    

    /**
     * Test case for patchOrderStatus
     *
     * .
     *
     */
    public function testPatchOrderStatus()
    {
    }
    

    /**
     * Test case for patchProduct
     *
     * .
     *
     */
    public function testPatchProduct()
    {
    }
    

    /**
     * Test case for patchProductCategory
     *
     * .
     *
     */
    public function testPatchProductCategory()
    {
    }
    

    /**
     * Test case for patchProductStockStatus
     *
     * .
     *
     */
    public function testPatchProductStockStatus()
    {
    }
    

    /**
     * Test case for patchProductsCategoryLink
     *
     * .
     *
     */
    public function testPatchProductsCategoryLink()
    {
    }
    

    /**
     * Test case for patchProductsLanguage
     *
     * .
     *
     */
    public function testPatchProductsLanguage()
    {
    }
    

    /**
     * Test case for patchProductsMediaFileLink
     *
     * .
     *
     */
    public function testPatchProductsMediaFileLink()
    {
    }
    

    /**
     * Test case for patchProductsMetaData
     *
     * .
     *
     */
    public function testPatchProductsMetaData()
    {
    }
    

    /**
     * Test case for patchProductsVariant
     *
     * .
     *
     */
    public function testPatchProductsVariant()
    {
    }
    

    /**
     * Test case for patchProductsVariantsAttributeValues
     *
     * .
     *
     */
    public function testPatchProductsVariantsAttributeValues()
    {
    }
    

    /**
     * Test case for patchProductsVariantsPricelistPrice
     *
     * .
     *
     */
    public function testPatchProductsVariantsPricelistPrice()
    {
    }
    

    /**
     * Test case for patchProductsVatRate
     *
     * .
     *
     */
    public function testPatchProductsVatRate()
    {
    }
    

    /**
     * Test case for patchTagOnCustomerBy
     *
     * .
     *
     */
    public function testPatchTagOnCustomerBy()
    {
    }
    

    /**
     * Test case for putAttribute
     *
     * .
     *
     */
    public function testPutAttribute()
    {
    }
    

    /**
     * Test case for putCustomer
     *
     * .
     *
     */
    public function testPutCustomer()
    {
    }
    

    /**
     * Test case for putCustomerAddress
     *
     * .
     *
     */
    public function testPutCustomerAddress()
    {
    }
    

    /**
     * Test case for putMediaFile
     *
     * .
     *
     */
    public function testPutMediaFile()
    {
    }
    

    /**
     * Test case for putOrder
     *
     * .
     *
     */
    public function testPutOrder()
    {
    }
    

    /**
     * Test case for putOrderAddress
     *
     * .
     *
     */
    public function testPutOrderAddress()
    {
    }
    

    /**
     * Test case for putOrderExternalService
     *
     * .
     *
     */
    public function testPutOrderExternalService()
    {
    }
    

    /**
     * Test case for putOrderItem
     *
     * .
     *
     */
    public function testPutOrderItem()
    {
    }
    

    /**
     * Test case for putOrderStatus
     *
     * .
     *
     */
    public function testPutOrderStatus()
    {
    }
    

    /**
     * Test case for putProduct
     *
     * .
     *
     */
    public function testPutProduct()
    {
    }
    

    /**
     * Test case for putProductCategory
     *
     * .
     *
     */
    public function testPutProductCategory()
    {
    }
    

    /**
     * Test case for putProductStockStatus
     *
     * .
     *
     */
    public function testPutProductStockStatus()
    {
    }
    

    /**
     * Test case for putProductsCategoryLink
     *
     * .
     *
     */
    public function testPutProductsCategoryLink()
    {
    }
    

    /**
     * Test case for putProductsLanguage
     *
     * .
     *
     */
    public function testPutProductsLanguage()
    {
    }
    

    /**
     * Test case for putProductsMediaFileLink
     *
     * .
     *
     */
    public function testPutProductsMediaFileLink()
    {
    }
    

    /**
     * Test case for putProductsMetaData
     *
     * .
     *
     */
    public function testPutProductsMetaData()
    {
    }
    

    /**
     * Test case for putProductsVariant
     *
     * .
     *
     */
    public function testPutProductsVariant()
    {
    }
    

    /**
     * Test case for putProductsVariantsAttributeValues
     *
     * .
     *
     */
    public function testPutProductsVariantsAttributeValues()
    {
    }
    

    /**
     * Test case for putProductsVariantsPricelistPrice
     *
     * .
     *
     */
    public function testPutProductsVariantsPricelistPrice()
    {
    }
    

    /**
     * Test case for putProductsVatRate
     *
     * .
     *
     */
    public function testPutProductsVatRate()
    {
    }
    

    /**
     * Test case for putTagOnCustomer
     *
     * .
     *
     */
    public function testPutTagOnCustomer()
    {
    }
    

    /**
     * Test case for removeAddressFromCustomer
     *
     * .
     *
     */
    public function testRemoveAddressFromCustomer()
    {
    }
    

    /**
     * Test case for removeTagFromCustomer
     *
     * .
     *
     */
    public function testRemoveTagFromCustomer()
    {
    }
    
}

